name: Docker Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files before build
        run: ls

      - name: Docker Login
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/htmlImage .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/htmlImage

      - name: Run Docker container
        run: docker run -d --name my_container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/htmlImage

      - name: Pull Docker image (optional)
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/htmlImage

